### ISSUE TITLE
spot checks in borgmatic aren't supported by exporter?

### ISSUE THREAD

**Issue by johnny2678** [maxim-mityutko/borgmatic-exporter#13]
Thanks for this. Just tried to set it up and it doesn't seem to like the spot checks that are supported by Borgmatic.

exported log:
```
summary:
/etc/borg/config/photos.yml: Error parsing configuration file
An error occurred while parsing a configuration file at /etc/borg/config/photos.yml:
At 'checks[1]': Additional properties are not allowed ('count_tolerance_percentage', 'data_sample_percentage', 'data_tolerance_percentage' were unexpected)
At 'checks[1].name': 'spot' is not one of ['repository', 'archives', 'data', 'extract', 'disabled']
```

config file is valid according to borgmatic:
```
summary:
All configuration files are valid
```

I can work around it as I'm not sure I need spot check.  Just bringing it up in case it's not a known issue.  Maybe support can be added in the future.

**Comment by maxim-mityutko** [comment]
Thank you for the interest in the project! 
As far as I can tell the feature for spot checks was added in [borgmatic 1.8.10](https://torsion.org/borgmatic/docs/how-to/deal-with-very-large-backups/#spot-check). I have not updated to that version yet, and also if you are using Docker, the image is based on 1.8.8.
I need to make a few changes to the project in order to support 1.8.10 or higher, as they changed the entrypoint for the base image, then I'll be able to properly test the `spot` functionality.

**Comment by johnny2678** [comment]
> if you are using Docker, the image is based on 1.8.8.

if this is the official repo `http://ghcr.io/borgmatic-collective/borgmatic`, it as at 1.8.11 now.

I could be wrong... I just found borgmatic and have been obsessed with it for days now.  Setting up monitoring was what led me to your project.  Not looking for special treatment.  When you get around to updating, I'll definitely check it out! thx.

**Comment by maxim-mityutko** [comment]
@johnny2678 I've made 2 new releases:
- v0.2.4 - borgmatic 1.8.11
- v0.2.5 - borgmatic 1.8.13

There are no changes in the exporter code, just the base images and a few things to make everything work with s6.

As far as I can tell, everything is working. At least based on the configurations that I have. Please poke around when you have time, and let me know if everything works as expected.
